# Generated by Django 5.1.1 on 2025-07-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='vote_type',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')]),
        ),
    ]
